export const TownHallDataTest = {
  level: 1,
  picture: "",
  data: {
    armyBuildings: {
      armyCamp: 0,
      barracks: 0,
      darkBarracks: 0,
      laboratory: 0,
      spellFactory: 0,
      darkSpellFactory: 0,
      blacksmith: 0,
      workshop: 0,
      petHouse: 0,
      heroHall: 0,
      helperHut: 0,
      boBsHut: 0,
    },
    defensiveBuildings: {
      cannon: 0,
      archerTower: 0,
      builderHut: 0,
      walls: 0,
      mortar: 0,
      airDefense: 0,
      wizardTower: 0,
      airSweeper: 0,
      hiddenTesla: 0,
      bombTower: 0,
      xBow: 0,
      infernoTower: 0,
      eagleArtillery: 0,
      scattershot: 0,
      spellTower: 0,
      monolith: 0,
      multiArcherTower: 0,
      ricochetCannon: 0,
      firespitter: 0,
    },
    trapBuildings: {
      bomb: 0,
      springTrap: 0,
      airBomb: 0,
      giantBomb: 0,
      seekingAirMine: 0,
      skeletonTrap: 0,
      tornadoTrap: 0,
    },
    heroes: {
      barbarianKing: 0,
      archerQueen: 0,
      grandWarden: 0,
      royalChampion: 0,
      minionPrince: 0,
    },
    resourceBuildings: {
      goldMine: 0,
      elixirCollector: 0,
      goldStorage: 0,
      elixirStorage: 0,
      darkElixirDrill: 0,
      darkElixirStorage: 0,
      clanCastle: 0,
    },
    laboratoryUpgrades: {
      elixirUpgrades: {
        barbarian: 0,
        archer: 0,
        giant: 0,
        goblin: 0,
        wallBreaker: 0,
        balloon: 0,
        wizard: 0,
        healer: 0,
        dragon: 0,
        pekka: 0,
        babyDragon: 0,
        miner: 0,
        electroDragon: 0,
        yeti: 0,
        dragonRider: 0,
        electroTitan: 0,
        rootRider: 0,
        thrower: 0,
        lightningSpell: 0,
        healingSpell: 0,
        rageSpell: 0,
        jumpSpell: 0,
        freezeSpell: 0,
        cloneSpell: 0,
        invisibilitySpell: 0,
        recallSpell: 0,
        reviveSpell: 0,
      },
      darkElixirUpgrades: {
        minion: 0,
        hogRider: 0,
        valkyrie: 0,
        golem: 0,
        witch: 0,
        lavaHound: 0,
        bowler: 0,
        iceGolem: 0,
        headhunter: 0,
        apprenticeWarden: 0,
        druid: 0,
        poisonSpell: 0,
        earthquakeSpell: 0,
        hasteSpell: 0,
        skeletonSpell: 0,
        batSpell: 0,
        overgrowthSpell: 0,
      },
      siegeMachineUpgrades: {
        wallWrecker: 0,
        battleBlimp: 0,
        stoneSlammer: 0,
        siegeBarracks: 0,
        logLauncher: 0,
        flameFlinger: 0,
        battleDrill: 0,
      },
    },
  },
};
