import * as Yup from "yup";
export const TownHallValidation = Yup.object({
  level: Yup.number()
    .min(1, "Level must be at least 1")
    .required("Level is required"),
  picture: Yup.string()
    .url("Picture must be a valid URL")
    .required("Picture is required"),
  data: Yup.object().shape({
    armyBuildings: Yup.object().shape({
      armyCamp: Yup.number().required("Required"),
      barracks: Yup.number().required("Required"),
      darkBarracks: Yup.number().required("Required"),
      laboratory: Yup.number().required("Required"),
      spellFactory: Yup.number().required("Required"),
      darkSpellFactory: Yup.number().required("Required"),
      blacksmith: Yup.number().required("Required"),
      workshop: Yup.number().required("Required"),
      petHouse: Yup.number().required("Required"),
      heroHall: Yup.number().required("Required"),
      helperHut: Yup.number().required("Required"),
      boBsHut: Yup.number().required("Required"),
    }),
    defensiveBuildings: Yup.object().shape({
      cannon: Yup.number().required("Required"),
      archerTower: Yup.number().required("Required"),
      builderHut: Yup.number().required("Required"),
      walls: Yup.number().required("Required"),
      mortar: Yup.number().required("Required"),
      airDefense: Yup.number().required("Required"),
      wizardTower: Yup.number().required("Required"),
      airSweeper: Yup.number().required("Required"),
      hiddenTesla: Yup.number().required("Required"),
      bombTower: Yup.number().required("Required"),
      xBow: Yup.number().required("Required"),
      infernoTower: Yup.number().required("Required"),
      eagleArtillery: Yup.number().required("Required"),
      scattershot: Yup.number().required("Required"),
      spellTower: Yup.number().required("Required"),
      monolith: Yup.number().required("Required"),
      multiArcherTower: Yup.number().required("Required"),
      ricochetCannon: Yup.number().required("Required"),
      firespitter: Yup.number().required("Required"),
    }),
    trapBuildings: Yup.object().shape({
      bomb: Yup.number().required("Required"),
      springTrap: Yup.number().required("Required"),
      airBomb: Yup.number().required("Required"),
      giantBomb: Yup.number().required("Required"),
      seekingAirMine: Yup.number().required("Required"),
      skeletonTrap: Yup.number().required("Required"),
      tornadoTrap: Yup.number().required("Required"),
    }),
    heroes: Yup.object().shape({
      barbarianKing: Yup.number().required("Required"),
      archerQueen: Yup.number().required("Required"),
      grandWarden: Yup.number().required("Required"),
      royalChampion: Yup.number().required("Required"),
      minionPrince: Yup.number().required("Required"),
    }),
    resourceBuildings: Yup.object().shape({
      goldMine: Yup.number().required("Required"),
      elixirCollector: Yup.number().required("Required"),
      goldStorage: Yup.number().required("Required"),
      elixirStorage: Yup.number().required("Required"),
      darkElixirDrill: Yup.number().required("Required"),
      darkElixirStorage: Yup.number().required("Required"),
      clanCastle: Yup.number().required("Required"),
    }),
    laboratoryUpgrades: Yup.object().shape({
      elixirUpgrades: Yup.object().shape({
        barbarian: Yup.number().required("Required"),
        archer: Yup.number().required("Required"),
        giant: Yup.number().required("Required"),
        goblin: Yup.number().required("Required"),
        wallBreaker: Yup.number().required("Required"),
        balloon: Yup.number().required("Required"),
        wizard: Yup.number().required("Required"),
        healer: Yup.number().required("Required"),
        dragon: Yup.number().required("Required"),
        pekka: Yup.number().required("Required"),
        babyDragon: Yup.number().required("Required"),
        miner: Yup.number().required("Required"),
        electroDragon: Yup.number().required("Required"),
        yeti: Yup.number().required("Required"),
        dragonRider: Yup.number().required("Required"),
        electroTitan: Yup.number().required("Required"),
        rootRider: Yup.number().required("Required"),
        thrower: Yup.number().required("Required"),
        lightningSpell: Yup.number().required("Required"),
        healingSpell: Yup.number().required("Required"),
        rageSpell: Yup.number().required("Required"),
        jumpSpell: Yup.number().required("Required"),
        freezeSpell: Yup.number().required("Required"),
        cloneSpell: Yup.number().required("Required"),
        invisibilitySpell: Yup.number().required("Required"),
        recallSpell: Yup.number().required("Required"),
        reviveSpell: Yup.number().required("Required"),
      }),
      darkElixirUpgrades: Yup.object().shape({
        minion: Yup.number().required("Required"),
        hogRider: Yup.number().required("Required"),
        valkyrie: Yup.number().required("Required"),
        golem: Yup.number().required("Required"),
        witch: Yup.number().required("Required"),
        lavaHound: Yup.number().required("Required"),
        bowler: Yup.number().required("Required"),
        iceGolem: Yup.number().required("Required"),
        headhunter: Yup.number().required("Required"),
        apprenticeWarden: Yup.number().required("Required"),
        druid: Yup.number().required("Required"),
        poisonSpell: Yup.number().required("Required"),
        earthquakeSpell: Yup.number().required("Required"),
        hasteSpell: Yup.number().required("Required"),
        skeletonSpell: Yup.number().required("Required"),
        batSpell: Yup.number().required("Required"),
        overgrowthSpell: Yup.number().required("Required"),
      }),
      siegeMachineUpgrades: Yup.object().shape({
        wallWrecker: Yup.number().required("Required"),
        battleBlimp: Yup.number().required("Required"),
        stoneSlammer: Yup.number().required("Required"),
        siegeBarracks: Yup.number().required("Required"),
        logLauncher: Yup.number().required("Required"),
        flameFlinger: Yup.number().required("Required"),
        battleDrill: Yup.number().required("Required"),
      }),
    }),
  }),
});
